name: reslocate_house_listing
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.0.0   # Keep it at 1.0.0 if you want to use the latest, else downgrade to 0.6.6
  image_picker: ^0.8.7+4     # Updated to latest version
  fluttertoast: ^8.0.8
  cupertino_icons: ^1.0.6
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
